### ISSUE TITLE
to_data_frame() got an unexpected keyword argument 'scaling_time'

### ISSUE THREAD

**Issue by mehranrkia** [emadeldeen24/ADAST#2]
Hello, I got the following error on PC in Windows 11 and i have already installed the latest version of pandas and numpy and mne.

D:/Desktop/Pattern Project/Project_Pattern/Dataset/PSG/SHHS1\shhs1-200097.edf
Extracting EDF parameters from D:\Desktop\Pattern Project\Project_Pattern\Dataset\PSG\SHHS1\shhs1-200097.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 3959999  =      0.000 ... 31679.992 secs...
Traceback (most recent call last):
  File "d:\Desktop\Pattern Project\Project_Pattern\Code\prepare_shhs.py", line 137, in <module>
    main()
  File "d:\Desktop\Pattern Project\Project_Pattern\Code\prepare_shhs.py", line 65, in main
    raw_ch_df = raw.to_data_frame(scaling_time=sampling_rate)[select_ch]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: to_data_frame() got an unexpected keyword argument 'scaling_time'

**Comment by emadeldeen24** [comment]
I used `mne=='0.20.7`

**Comment by mehranrkia** [comment]
Thanks! This solved the problem.

**Comment by cherishleon** [comment]
> I used `mne=='0.20.7`

Thanks
