### ISSUE TITLE
dataloader

### ISSUE THREAD

**Issue by mehranrkia** [emadeldeen24/ADAST#3]
Hello
Can you please explain about dataloader file? I couldn't load the downloaded dataset in the dataloader file. 
How should i split the data and put it in the following part? 

def data_generator(data_path, domain_id, configs):
    # loading path
    train_dataset = torch.load(os.path.join(data_path, "train_" + domain_id + ".pt"))
    valid_dataset = torch.load(os.path.join(data_path, "val_" + domain_id + ".pt"))
    test_dataset = torch.load(os.path.join(data_path, "test_" + domain_id + ".pt"))

    # Loading datasets
    train_dataset = Load_Dataset(train_dataset)
    valid_dataset = Load_Dataset(valid_dataset)
    test_dataset = Load_Dataset(test_dataset)

**Comment by emadeldeen24** [comment]
you can split the data files into train/test/val splits then combine them into .pt files
